#! /usr/bin/env node

require('dotenv-safe').load();
let CF = require('cloudflare');
let SUBDOMAIN = require('yargs').argv._[0];

let client = new CF({
  email: CF_EMAIL,
  key: CF_KEY
});

let rr = CF.DNSRecord.create({
  zone_id: process.env.CF_ZONE_ID,
  type: 'CNAME',
  name: SUBDOMAIN,
  content: 'clive.io',
  proxied: true
});
