#!/bin/sh

if [ "$1" = "reg" ] || [ "$1" = "register" ]; then
  if [ -z "$2" ]; then
    echo "Missing parameters"
  elif [ -z "$3" ]; then
    curl -sS "localhost:10000/register/$2"
  else
    curl -sS "localhost:10000/register/$2/$3"
  fi
elif [ "$1" = "unreg" ] || [ "$1" = "unregister" ]; then
  if [ ! -z "$2" ]; then
    curl -sS "localhost:10000/unregister/$2"
  else
    echo "Missing parameters"
  fi
elif [ "$1" = "create" ]; then
  if [ -z "$2" ]; then
    echo "Missing parameters"
  else
    export PORT=$(curl -sS "localhost:10000/register/$2")
    echo "Port $PORT allocated and registered to $2."
    pm2 start npm --name="router:$2" --log-date-format="YYYY-MM-DD HH:mm Z" -- start
    shift 2 # discard "create" and the already-registered route
    for route in "$@"
    do
      curl -sS "localhost:10000/register/$route/$PORT"
    done
  fi
elif [ "$1" = "delete" ]; then
  if [ -z "$2" ]; then
    echo "Missing parameters"
  else
    pm2 delete "router:$2"
    shift # discard "delete"
    for route in "$@"
    do
      curl -sS "localhost:10000/unregister/$route"
    done
  fi
elif [ -z "$1" ] || [ "$1" = "show" ]; then
  curl -sS localhost:10000
else
  echo "Unknown router command"
fi
