#!/bin/sh

if [ "$1" = "reg" ] || [ "$1" = "register" ]; then
  if [ ! -z "$2" ] && [ ! -z "$3" ]; then
    curl -sS "localhost:10000/register/$2/$3"
  else
    echo "Missing parameters"
  fi
elif [ "$1" = "unreg" ] || [ "$1" = "unregister" ]; then
  if [ ! -z "$2" ]; then
    curl -sS "localhost:10000/unregister/$2"
  else
    echo "Missing parameters"
  fi
elif [ "$1" = "create" ]; then
  export PORT=$(curl "localhost:10000/register/$2")
  echo "Port $PORT allocated and registered."
  pm2 start npm --name="$2" -- start
elif [ "$1" = "delete" ]; then
  curl -sS "localhost:10000/unregister/$2"
  pm2 delete "$2"
elif [ -z "$1" ] || [ "$1" = "show" ]; then
  curl -sS localhost:10000
else
  echo "Unknown router command"
fi
